### ISSUE TITLE
Login error message is not displayed in iPhone

### ISSUE THREAD

**Issue by tochi-y** [personium/app-cc-home#240]
## Expected

In chrome mobile simulator, the error message is displayed.

<img src="https://user-images.githubusercontent.com/32325140/60779360-6a68a800-a175-11e9-9a5a-f9a433551cb5.png" width="200" />

## Acctual iPhone (Chrome or Safari)

In iPhone, the error message is not displayed.

<img src="https://user-images.githubusercontent.com/32325140/60779760-e2839d80-a176-11e9-9508-b1cf6a402c1e.png" width="200" />

**Comment by dixonsiu** [comment]
Chrome simulator does not show the exact height, therefore, need to add hard coded responsive CSS.
