### ISSUE TITLE
No way to determine which version (regular or Biz) should the user see

### ISSUE THREAD

**Issue by dixonsiu** [personium/app-cc-home#65]
Since Personium does not have any way to determine which is which.
I am working on a proposal to solve the following issues.

1. There is no automated way to determine which HomeApp the User (data subject, object, passive user) or organization (data consumer/provider) must use.  
Currently either version of HomeApp can be logged in.  

1. In HomeApp, the list of installed apps contains HomeApp itself and accidentaly got rendered.  
Current hotfix is not to render the app with the same box name as the running app (HomeApp).

**Comment by dixonsiu** [comment]
# Proposal  
Introduce a new key/value pair ("CellType": <cell's type>) to profile.json so that the app can determine the rendering routine properly.  

There are two major catogories of cell type.  
- "User"
- "App"

## Catogorized by "User" Type  
- "person"  
Data subject which is supposed to be a "real" person.  
**Issue No.1 solved: HomeApp is the default app.**  

        {
            "DisplayName":"Guest",
            "Description":"",
            "Image": ...
            "CellType": "person"
        }

- "organization"  
Data consumer or provider which is an organziation.  
**Issue No.1 solved: HomeApp for Biz is the default app.**  
Examples: P's Mart  

        {
            "DisplayName":　"P's Mart (Wakaba Branch)",
            "Description":　"",
            "Image": ...
            "CellType": "organization"
        }

- "object"  
Data subject which is an object.  
Examples: car, apartment   
- "passive"  
Passive user cell  
Examples: infants, elderly  

## Catogorized by App Type  
Except AdminApp, all other app types (CellApp/ClientApp/BizApp) got installed onto the cell as box.  

- "AdminApp"  
Management app that can display all the details inside a unit cell or regular cell.    
Examples: UnitManager, CellManager  
- "CellApp"  
Management app that display client/business apps  
**Issue No.2: Basice rule for a CellApp is not to display any CellApp.**  
Examples: HomeApp, HomeApp for Biz

        {
            "DisplayName":"HomeApp",
            "Description":"ホームアプリセル",
            "Image": ...
            "CellType": "CellApp"
        }

- "ClientApp"  
Client app for data subject.  
Examples: MyBoard, Calorie Smile, Wakaba Municipal Info Bank  

        {
            "DisplayName": {
                "en": "MyBoard", 
                "ja": "マイボード"
            },
            "Description": {
                "en": "Demo application (MyBoard).",
                "ja": "デモアプリ「マイボード」"
            },
            "Image": ...
            "CellType": "ClientApp"
        }

- "BizApp"  
Business app for data consumer/provider.  
Examples: Wakaba Municipal Info Bank for Biz

        {
            "DisplayName": { 
                "en": "Wakaba Municipal Info Bank",
                "ja": "わかば市情報バンク" 
            },
            "Description": { 
                "en": "Admin application for Wakaba Municipal Info Bank.", 
                "ja": "わかば市情報バンクアプリセルです。" 
            },
            "Image": ...
            "CellType": "BizApp"
        }

**Comment by shimono** [comment]
I think the newly introduced key "CellType" should rather be  just "Type" because profile.json is a file for describing the profile of the Cell.

**Comment by shimono** [comment]
We should not probably introduce type value "passive".  Instead it should be handled with another key, e.g. ("Passive": true or "Active": false) later.   A person, organization or object..  may be passive, whereas other person, organization or object..  maybe active.

**Comment by shimono** [comment]
Word choice "App"/"Schema"/"Client" should be carefully considered.  Also, the polymorphism may be taken into account, i.e. by introducing a convention like below, forward matching can extract super-class of the "Type" defined.

-----------
Client.Cell.Personal  - home-app type client for personal use
Client.Cell.Business  - home-app type client for business use
Client.App.Personal  - application client for personal use
Client.App.Business - application  client for biz use
-----------

We should also probably consider the "sub-schema". (The new notion we discussed the other day to handle multiple views in same app for multiple user roles, e.g.  teacher, student etc.)

Isn't that "Personal"/"Business" thing handled with sub-schema, rather than Cell's "Type"? 
I do not have my answer for this yet.

**Comment by dixonsiu** [comment]
To avoid confusion, I prefer CellType because when new comers might think that is application type when the cell is for an application.

**Comment by dixonsiu** [comment]
Can't agree with you on the following names. Client app makes sense but client cell does not make any connection with HomeApp as an app for client to manage a cell. Let's discuss it during Sprint meeting
- Client.Cell.Personal
- Client.Cell.Business

**Comment by dixonsiu** [comment]
The following commits solve this issue.  

1. Commit 7267f99d9d5247462351f7bd028d1a71d7873290
1. Commit 6354bee89b0e11fed52c2d05c0dfe743fddabff3
1. Commit f039aa954294e7537409039cc6d4842123e4f4ed
